// 14-day Rioplatense Spanish course. Each phrase: [spanish, english, pronunciation]
// Dialogue: they = what the local says; options = your replies; answer = index of best reply.
const COURSE = [
  {
    day: 1, title: "Survival & money", place: "Everywhere",
    tip: "You know hola/gracias/numbers — this is the stuff that rescues you. Argentines speak fast; asking them to slow down is normal. Cash ('efectivo') often gets a discount.",
    phrases: [
      ["No entiendo", "I don't understand", "noh en-TYEN-doh"],
      ["Más despacio, por favor", "Slower, please", "mahs des-PAH-syoh, por fah-VOR"],
      ["¿Hablás inglés?", "Do you speak English?", "ah-BLAHS een-GLESS?"],
      ["¿Cómo se dice…?", "How do you say…?", "KOH-moh seh DEE-seh?"],
      ["¿Me podés ayudar?", "Can you help me?", "meh poh-DESS ah-yoo-DAR?"],
      ["¿Dónde está el baño?", "Where is the bathroom?", "DOHN-deh es-TAH el BAH-nyoh?"],
      ["¿Cuánto sale?", "How much is it?", "KWAHN-toh SAH-leh?"],
      ["¿Aceptan tarjeta?", "Do you take card?", "ah-SEP-tahn tar-HEH-tah?"],
      ["¿Hay descuento en efectivo?", "Is there a cash discount?", "eye des-KWEN-toh en eh-fek-TEE-voh?"],
      ["¿Todo bien? — Todo bien, ¿y vos?", "All good? — All good, and you?", "TOH-doh BYEN? ee VOHS?"],
    ],
    dialogue: [
      { they: "¡Buenas! ¿Todo bien?", options: ["Todo bien, gracias. ¿Y vos?", "De nada.", "Chau."], answer: 0, note: "'Vos' replaces 'tú' in Argentina." },
      { they: "(very fast) …y-entonces-si-querés-podés-ir-por-ahí…", options: ["Chau.", "Perdón, más despacio, por favor.", "Buenas noches."], answer: 1 },
      { they: "Son quince mil. En efectivo, trece mil quinientos.", options: ["Perfecto, pago en efectivo.", "¿Dónde está el baño?", "Me llamo Hannah."], answer: 0, note: "15,000 vs 13,500 in cash — a 10% discount." },
    ],
  },
  {
    day: 2, title: "Café culture", place: "Café (Buenos Aires)",
    tip: "At Café Tortoni (BA's grand 1858 café) or Argot, order a 'cortado' (espresso + a little milk) with 'medialunas' (small sweet croissants). Nobody rushes you — ask for the bill when you're ready.",
    phrases: [
      ["Un café con leche, por favor", "A coffee with milk, please", "oon kah-FEH kohn LEH-cheh"],
      ["Un cortado", "Espresso with a splash of milk", "oon kor-TAH-doh"],
      ["Dos medialunas", "Two croissants", "dohs meh-dyah-LOO-nahs"],
      ["Para tomar acá", "For here", "PAH-rah toh-MAR ah-KAH"],
      ["Para llevar", "To go", "PAH-rah sheh-VAR"],
      ["Quisiera…", "I would like…", "kee-SYEH-rah…"],
      ["¿Me traés…?", "Can you bring me…?", "meh trah-ESS…?"],
      ["Un agua sin gas", "A still water", "oon AH-gwah seen gahs"],
      ["¿Tienen wifi?", "Do you have wifi?", "TYEH-nen WEE-fee?"],
      ["La cuenta, por favor", "The bill, please", "lah KWEN-tah, por fah-VOR"],
    ],
    dialogue: [
      { they: "¡Hola! ¿Qué van a tomar?", options: ["Dos cortados y dos medialunas, por favor.", "La cuenta.", "Somos de Estados Unidos."], answer: 0, note: "'¿Qué van a tomar?' = 'What will you have (to drink)?'" },
      { they: "¿Para tomar acá o para llevar?", options: ["Para llevar, por favor.", "Sí.", "Mil."], answer: 0 },
    ],
  },
  {
    day: 3, title: "Reading the menu", place: "Any restaurant or café",
    tip: "Menus are 'la carta'. Lunch spots often have a 'menú del día' (set lunch). Empanadas are ordered by the dozen or half dozen — 'media docena'.",
    phrases: [
      ["Carne / pollo / pescado", "Beef / chicken / fish", "KAR-neh / POH-shoh / pes-KAH-doh"],
      ["Empanadas de carne / jamón y queso", "Beef / ham & cheese empanadas", "em-pah-NAH-dahs deh KAR-neh / hah-MOHN ee KEH-soh"],
      ["Media docena", "Half a dozen", "MEH-dyah doh-SEH-nah"],
      ["Milanesa", "Breaded cutlet (schnitzel)", "mee-lah-NEH-sah"],
      ["Choripán", "Chorizo sandwich", "choh-ree-PAHN"],
      ["Papas fritas / ensalada", "Fries / salad", "PAH-pahs FREE-tahs / en-sah-LAH-dah"],
      ["Con chimichurri", "With chimichurri", "kohn chee-mee-CHOO-rree"],
      ["Dulce de leche", "Caramel spread (it's everywhere)", "DOOL-seh deh LEH-cheh"],
      ["¿Qué es esto?", "What is this?", "keh ess ESS-toh?"],
      ["¿Tienen menú del día?", "Do you have a set lunch?", "TYEH-nen meh-NOO del DEE-ah?"],
    ],
    dialogue: [
      { they: "¿Qué les traigo?", options: ["Media docena de empanadas de carne, por favor.", "Un pasaje a Bariloche.", "La llave."], answer: 0 },
      { they: "El menú del día es milanesa con papas fritas, doce mil pesos.", options: ["Dos, por favor. ¿Incluye bebida?", "Perdí mi celular.", "Solo de bajada."], answer: 0, note: "'Doce mil' = 12,000. 'Bebida' = drink." },
    ],
  },
  {
    day: 4, title: "Restaurant: ordering", place: "Parrilla / restaurant",
    tip: "Dinner starts late — your 7pm Don Julio reservation will be early by local standards! At a 'parrilla' (steakhouse) try 'bife de chorizo' (sirloin) and 'provoleta' (grilled cheese). Cooking: 'jugoso' = medium-rare, 'a punto' = medium.",
    phrases: [
      ["Tenemos una reserva a las siete", "We have a reservation at seven", "teh-NEH-mohs OO-nah rreh-SEHR-vah ah lahs SYEH-teh"],
      ["¿Me pasás la carta?", "Can I have the menu?", "meh pah-SAHS lah KAR-tah?"],
      ["¿Qué me recomendás?", "What do you recommend?", "keh meh reh-koh-men-DAHS?"],
      ["Para mí, el bife de chorizo", "For me, the sirloin", "PAH-rah mee, el BEE-feh deh choh-REE-soh"],
      ["Jugoso / a punto / bien cocido", "Rare / medium / well done", "hoo-GOH-soh / ah POON-toh / byen koh-SEE-doh"],
      ["Para compartir", "To share", "PAH-rah kohm-par-TEER"],
      ["Una botella de Malbec", "A bottle of Malbec", "OO-nah boh-TEH-shah deh mahl-BEK"],
      ["Soy vegetariano/a", "I'm vegetarian", "soy veh-heh-tah-RYAH-noh"],
      ["Soy alérgico/a a…", "I'm allergic to…", "soy ah-LEHR-hee-koh ah…"],
      ["Nada más, gracias", "Nothing else, thanks", "NAH-dah mahs, GRAH-syahs"],
    ],
    dialogue: [
      { they: "Buenas noches, ¿tienen reserva?", options: ["Sí, a las siete, a nombre de Nelson.", "Jugoso.", "Nada más."], answer: 0 },
      { they: "¿Cómo querés la carne?", options: ["Para compartir.", "A punto, por favor.", "Una mesa."], answer: 1, note: "'La carne' = the meat." },
      { they: "¿Algo más?", options: ["Nada más, gracias.", "Hola.", "No entiendo el baño."], answer: 0 },
    ],
  },
  {
    day: 5, title: "Restaurant: paying & problems", place: "Restaurant",
    tip: "Tip ('propina') about 10%, usually in cash. Some places add a 'cubierto' (cover charge) for bread — that's normal, not a tip.",
    phrases: [
      ["La cuenta, por favor", "The bill, please", "lah KWEN-tah"],
      ["¿Está incluida la propina?", "Is the tip included?", "es-TAH een-kloo-EE-dah lah proh-PEE-nah?"],
      ["¿Qué es el cubierto?", "What's the cover charge?", "keh ess el koo-BYER-toh?"],
      ["¿Podemos pagar separado?", "Can we pay separately?", "poh-DEH-mohs pah-GAR seh-pah-RAH-doh?"],
      ["Está riquísimo", "It's delicious", "es-TAH ree-KEE-see-moh"],
      ["Esto no es lo que pedí", "This isn't what I ordered", "ESS-toh noh ess loh keh peh-DEE"],
      ["Falta un plato", "A dish is missing", "FAHL-tah oon PLAH-toh"],
      ["¿Me traés otro tenedor?", "Can you bring another fork?", "meh trah-ESS OH-troh teh-neh-DOR?"],
      ["Está frío", "It's cold", "es-TAH FREE-oh"],
      ["Todo perfecto, gracias", "Everything's perfect, thanks", "TOH-doh pehr-FEK-toh"],
    ],
    dialogue: [
      { they: "¿Qué tal todo?", options: ["Está riquísimo, gracias.", "Falta un tenedor de chorizo.", "Chau."], answer: 0, note: "'¿Qué tal todo?' = 'How is everything?'" },
      { they: "Acá tienen la cuenta.", options: ["¿Podemos pagar con tarjeta?", "Una mesa para dos.", "Más despacio."], answer: 0 },
    ],
  },
  {
    day: 6, title: "Bars & nightlife", place: "Bar (Buenos Aires)",
    tip: "Try 'Fernet con Coca' (the national drink) or a 'birra' (beer). Bars fill up after midnight. El Boliche de Roberto is a tiny, old tango bar — live music, walk-in, small tables. 'Che' = 'hey', used constantly.",
    phrases: [
      ["Una birra, por favor", "A beer, please", "OO-nah BEE-rrah"],
      ["Una pinta de IPA", "A pint of IPA", "OO-nah PEEN-tah deh EE-pah"],
      ["Un Fernet con Coca", "A Fernet and Coke", "oon fer-NET kohn KOH-kah"],
      ["Una copa de vino tinto", "A glass of red wine", "OO-nah KOH-pah deh VEE-noh TEEN-toh"],
      ["Otra ronda", "Another round", "OH-trah RROHN-dah"],
      ["¿A qué hora empieza el tango?", "What time does the tango start?", "ah keh OH-rah em-PYEH-sah el TAHN-goh?"],
      ["¡Salud!", "Cheers!", "sah-LOOD!"],
      ["Che, ¿qué onda?", "Hey, what's up?", "cheh, keh OHN-dah?"],
      ["¡Qué buena onda!", "So cool / great vibe", "keh BWEH-nah OHN-dah"],
      ["¿Hay lugar para dos?", "Is there room for two?", "eye loo-GAR PAH-rah dohs?"],
    ],
    dialogue: [
      { they: "Che, ¿qué onda? ¿Qué te sirvo?", options: ["Una birra y un Fernet con Coca, por favor.", "La cuenta del cubierto.", "Buen día."], answer: 0, note: "'¿Qué te sirvo?' = 'What can I get you?'" },
      { they: "¡Salud!", options: ["¡Salud!", "Perdón.", "De nada."], answer: 0 },
    ],
  },
  {
    day: 7, title: "Shopping", place: "Shops & markets (San Telmo)",
    tip: "At San Telmo's Sunday market, friendly haggling is OK. In regular shops, prices are fixed. 'Estoy mirando' gets salespeople to leave you alone politely.",
    phrases: [
      ["Estoy mirando, gracias", "I'm just looking, thanks", "es-TOY mee-RAHN-doh"],
      ["¿Tenés esto en otro talle?", "Do you have this in another size?", "teh-NESS ESS-toh en OH-troh TAH-sheh?"],
      ["¿Me lo puedo probar?", "Can I try it on?", "meh loh PWEH-doh proh-BAR?"],
      ["Más grande / más chico", "Bigger / smaller", "mahs GRAHN-deh / mahs CHEE-koh"],
      ["Me lo llevo", "I'll take it", "meh loh SHEH-voh"],
      ["¿Me hacés un precio?", "Can you give me a deal?", "meh ah-SESS oon PREH-syoh?"],
      ["Es un regalo", "It's a gift", "ess oon rreh-GAH-loh"],
      ["¿Tenés bolsa?", "Do you have a bag?", "teh-NESS BOHL-sah?"],
      ["¿A qué hora cierran?", "What time do you close?", "ah keh OH-rah SYEH-rrahn?"],
      ["Un kilo de… / cien gramos de…", "A kilo of… / 100 grams of…", "oon KEE-loh / syen GRAH-mohs"],
    ],
    dialogue: [
      { they: "Hola, ¿te puedo ayudar en algo?", options: ["Estoy mirando, gracias.", "Jugoso.", "Otra ronda."], answer: 0 },
      { they: "Este sale veinte mil.", options: ["¿Me hacés un precio si llevo dos?", "Somos dos.", "¡Salud!"], answer: 0, note: "'Si llevo dos' = 'if I take two'." },
    ],
  },
  {
    day: 8, title: "Hotel check-in", place: "Hotel / hostel",
    tip: "Alvear Palace (BA) is formal — staff may switch to English, but greeting in Spanish is appreciated. Have your booking name ready. Ask about luggage storage ('dejar las valijas') — useful on travel days (Oct 19 & 23).",
    phrases: [
      ["Tengo una reserva a nombre de…", "I have a reservation under…", "TEN-goh OO-nah rreh-SEHR-vah ah NOHM-breh deh…"],
      ["Para dos noches", "For two nights", "PAH-rah dohs NOH-chess"],
      ["¿A qué hora es el check-out?", "What time is check-out?", "ah keh OH-rah ess el check-out?"],
      ["¿Está incluido el desayuno?", "Is breakfast included?", "es-TAH een-kloo-EE-doh el deh-sah-YOO-noh?"],
      ["¿Cuál es la contraseña del wifi?", "What's the wifi password?", "kwahl ess lah kohn-trah-SEH-nyah?"],
      ["¿Podemos dejar las valijas?", "Can we leave our bags?", "poh-DEH-mohs deh-HAR lahs vah-LEE-hahs?"],
      ["La llave", "The key", "lah SHAH-veh"],
      ["No funciona el aire / la ducha", "The AC / shower doesn't work", "noh foon-SYOH-nah el EYE-reh / lah DOO-chah"],
      ["¿Me podés pedir un taxi?", "Can you call me a taxi?", "meh poh-DESS peh-DEER oon TAHK-see?"],
      ["Habitación", "Room", "ah-bee-tah-SYOHN"],
    ],
    dialogue: [
      { they: "Bienvenidos. ¿Tienen reserva?", options: ["Sí, a nombre de Nelson.", "Una birra.", "Me lo llevo."], answer: 0 },
      { they: "El desayuno es de siete a diez.", options: ["Perfecto. ¿Cuál es la contraseña del wifi?", "Jugoso, por favor.", "No, gracias, chau."], answer: 0 },
    ],
  },
  {
    day: 9, title: "Getting around", place: "Streets, taxis, subte",
    tip: "In La Boca, stick to Caminito and the busy streets, and take a taxi/Uber there and back. 'Cuadra' = city block — directions are given in blocks.",
    phrases: [
      ["¿Dónde está…?", "Where is…?", "DOHN-deh es-TAH…?"],
      ["¿Cómo llego a…?", "How do I get to…?", "KOH-moh SHEH-goh ah…?"],
      ["A la derecha / a la izquierda", "To the right / left", "ah lah deh-REH-chah / ees-KYEHR-dah"],
      ["Derecho", "Straight ahead", "deh-REH-choh"],
      ["Dos cuadras", "Two blocks", "dohs KWAH-drahs"],
      ["¿Está cerca o lejos?", "Is it near or far?", "es-TAH SEHR-kah oh LEH-hohs?"],
      ["A esta dirección, por favor", "To this address, please (taxi)", "ah ESS-tah dee-rek-SYOHN"],
      ["Acá está bien", "Here is fine (stop here)", "ah-KAH es-TAH byen"],
      ["El subte / el colectivo", "The subway / the bus", "el SOOB-teh / el koh-lek-TEE-voh"],
      ["Al aeropuerto, por favor", "To the airport, please", "ahl ah-eh-roh-PWEHR-toh"],
    ],
    dialogue: [
      { they: "Seguí derecho dos cuadras y después a la izquierda.", options: ["Gracias, ¿está lejos?", "Una mesa para dos.", "¡Salud!"], answer: 0, note: "'Seguí' = 'keep going', 'después' = 'then'." },
      { they: "(taxi driver) ¿Dónde los dejo?", options: ["Acá está bien, gracias.", "Para llevar.", "Mil."], answer: 0, note: "'¿Dónde los dejo?' = 'Where do I drop you off?'" },
    ],
  },
  {
    day: 10, title: "Travel days: airports & flights", place: "Airports (BA → El Calafate → Bariloche)",
    tip: "You have 3+ flights. Domestic flights in BA usually leave from Aeroparque (AEP), not Ezeiza (EZE) — double-check. Argentine airports use 24h time: 'trece cuarenta y cinco' = 1:45pm.",
    phrases: [
      ["¿Dónde se hace el check-in?", "Where is check-in?", "DOHN-deh seh AH-seh el check-in?"],
      ["Tenemos dos valijas", "We have two suitcases", "teh-NEH-mohs dohs vah-LEE-hahs"],
      ["Equipaje de mano", "Carry-on luggage", "eh-kee-PAH-heh deh MAH-noh"],
      ["¿Cuál es la puerta de embarque?", "Which is the boarding gate?", "kwahl ess lah PWEHR-tah deh em-BAR-keh?"],
      ["¿El vuelo está demorado?", "Is the flight delayed?", "el VWEH-loh es-TAH deh-moh-RAH-doh?"],
      ["¿A qué hora embarcamos?", "What time do we board?", "ah keh OH-rah em-bar-KAH-mohs?"],
      ["Ventanilla / pasillo", "Window / aisle", "ven-tah-NEE-shah / pah-SEE-shoh"],
      ["Perdimos la conexión", "We missed our connection", "pehr-DEE-mohs lah koh-nek-SYOHN"],
      ["¿Dónde está la parada de taxis?", "Where's the taxi stand?", "DOHN-deh es-TAH lah pah-RAH-dah deh TAHK-sees?"],
      ["Aeroparque / Ezeiza", "BA's domestic / international airports", "ah-eh-roh-PAR-keh / eh-SAY-sah"],
    ],
    dialogue: [
      { they: "¿Cuántas valijas despachan?", options: ["Dos valijas y equipaje de mano.", "Media docena.", "¡Salud!"], answer: 0, note: "'Despachar' = to check (a bag)." },
      { they: "El vuelo sale a las trece cuarenta y cinco, puerta cuatro.", options: ["Gracias. ¿Está demorado?", "Jugoso.", "Estoy mirando."], answer: 0, note: "13:45 = 1:45pm, gate 4." },
    ],
  },
  {
    day: 11, title: "Patagonia: El Chaltén", place: "El Chaltén (trails, buses)",
    tip: "Your hikes: Laguna Torre & Las Vueltas (Oct 20), Laguna de los Tres sunrise (Oct 21). Start Los Tres in the dark — headlamp! Weather changes fast; ask locals about wind ('viento'). ATMs often run out — bring cash!",
    phrases: [
      ["¿Dónde empieza el sendero?", "Where does the trail start?", "DOHN-deh em-PYEH-sah el sen-DEH-roh?"],
      ["¿Cuántas horas son?", "How many hours is it?", "KWAHN-tahs OH-rahs sohn?"],
      ["¿Es difícil?", "Is it hard?", "ess dee-FEE-seel?"],
      ["¿Cómo está el clima mañana?", "What's the weather tomorrow?", "KOH-moh es-TAH el KLEE-mah mah-NYAH-nah?"],
      ["Hay mucho viento", "It's very windy", "eye MOO-choh VYEN-toh"],
      ["Necesitamos un transfer al aeropuerto de El Calafate", "We need a transfer to El Calafate airport", "neh-seh-see-TAH-mohs oon TRAHNS-fer ahl ah-eh-roh-PWEHR-toh"],
      ["¿A qué hora sale el sol?", "What time is sunrise?", "ah keh OH-rah SAH-leh el sohl?"],
      ["¿Hay cajero automático?", "Is there an ATM?", "eye kah-HEH-roh ow-toh-MAH-tee-koh?"],
      ["Una vianda para llevar", "A packed lunch to go", "OO-nah VYAHN-dah PAH-rah sheh-VAR"],
      ["¡Qué lindo!", "How beautiful!", "keh LEEN-doh!"],
    ],
    dialogue: [
      { they: "Para Laguna de los Tres son unas ocho horas ida y vuelta.", options: ["¿Es difícil?", "Me lo llevo.", "Una birra."], answer: 0, note: "'Ida y vuelta' = 'round trip'." },
      { they: "El transfer al aeropuerto tarda tres horas.", options: ["Perfecto. Nuestro vuelo es a la una y cuarenta y cinco.", "Jugoso.", "Estoy mirando."], answer: 0, note: "'Tarda' = takes (time). 'Vuelo' = flight." },
    ],
  },
  {
    day: 12, title: "Patagonia: Bariloche", place: "Bariloche (Campanario, Mitre, breweries, lake)",
    tip: "Your plan: Cerro Campanario hike + chairlift down, chocolate crawl on Calle Mitre (Rapanui, Mamushka, La Chocolaterie, Benroth), breweries, tea houses, and a boat to Isla Victoria & Los Arrayanes.",
    phrases: [
      ["¿Dónde se toma la aerosilla?", "Where do you catch the chairlift?", "DOHN-deh seh TOH-mah lah ah-eh-roh-SEE-shah?"],
      ["Solo de bajada, por favor", "Just the ride down, please", "SOH-loh deh bah-HAH-dah"],
      ["¿Me das para probar?", "Can I have a taste?", "meh dahs PAH-rah proh-BAR?"],
      ["Chocolate amargo / con leche", "Dark / milk chocolate", "choh-koh-LAH-teh ah-MAR-goh / kohn LEH-cheh"],
      ["Un cuarto kilo de bombones", "A quarter kilo of chocolates", "oon KWAR-toh KEE-loh deh bohm-BOH-ness"],
      ["¿Qué cervezas artesanales tienen?", "What craft beers do you have?", "keh sehr-VEH-sahs ar-teh-sah-NAH-less TYEH-nen?"],
      ["Un té y algo dulce", "A tea and something sweet", "oon teh ee AHL-goh DOOL-seh"],
      ["Dos pasajes a Isla Victoria", "Two tickets to Isla Victoria", "dohs pah-SAH-hess ah EES-lah veek-TOH-ryah"],
      ["¿A qué hora vuelve el barco?", "What time does the boat return?", "ah keh OH-rah VWEL-veh el BAR-koh?"],
      ["¡Qué vista increíble!", "What an incredible view!", "keh VEES-tah een-kreh-EE-bleh!"],
    ],
    dialogue: [
      { they: "¿Ida y vuelta o solo de bajada?", options: ["Solo de bajada, por favor.", "Un cuarto kilo de trucha.", "Chau."], answer: 0, note: "'Bajada' = going down; 'subida' = going up." },
      { they: "¿Querés probar el amargo?", options: ["¡Sí, gracias! Está riquísimo.", "No funciona la ducha.", "Dos cuadras."], answer: 0 },
      { they: "El barco sale a las diez y vuelve a las cuatro.", options: ["Perfecto, dos pasajes, por favor.", "Para llevar.", "Jugoso."], answer: 0 },
    ],
  },
  {
    day: 13, title: "Problems & small talk", place: "Everywhere",
    tip: "Emergency number: 911. Pharmacy = 'farmacia'. For small talk, Argentines love talking about football, food, and travel — 'Me encanta Argentina' goes a long way.",
    phrases: [
      ["Perdí mi celular / pasaporte", "I lost my phone / passport", "pehr-DEE mee seh-loo-LAR / pah-sah-POR-teh"],
      ["Necesito una farmacia", "I need a pharmacy", "neh-seh-SEE-toh OO-nah far-MAH-syah"],
      ["Me siento mal", "I feel sick", "meh SYEN-toh mahl"],
      ["¡Ayuda!", "Help!", "ah-YOO-dah!"],
      ["Llamá a la policía", "Call the police", "shah-MAH ah lah poh-lee-SEE-ah"],
      ["Estamos de viaje diez días", "We're traveling for ten days", "es-TAH-mohs deh VYAH-heh dyess DEE-ahs"],
      ["Me encanta Argentina", "I love Argentina", "meh en-KAHN-tah ar-hen-TEE-nah"],
      ["¿Sos de acá?", "Are you from here?", "sohs deh ah-KAH?"],
      ["¿De qué cuadro sos?", "Which football team do you support?", "deh keh KWAH-droh sohs?"],
      ["Mucho gusto", "Nice to meet you", "MOO-choh GOOS-toh"],
    ],
    dialogue: [
      { they: "¿Es la primera vez que vienen a Argentina?", options: ["Sí, ¡me encanta Argentina!", "Necesito una farmacia de bife.", "Otra ronda."], answer: 0, note: "'Primera vez' = first time." },
      { they: "¿De qué cuadro sos?", options: ["¡De Boca! … o River. ¡No sé!", "Para llevar.", "Habitación."], answer: 0, note: "Boca vs River is THE rivalry. Expect laughter either way." },
    ],
  },
  {
    day: 14, title: "Final review: a full night out", place: "Review",
    tip: "Today mixes everything. Then use the Cheat Sheet tab during the trip. ¡Buen viaje!",
    phrases: [
      ["Una mesa para dos, por favor", "A table for two, please", "OO-nah MEH-sah PAH-rah dohs"],
      ["¿Qué me recomendás?", "What do you recommend?", "keh meh reh-koh-men-DAHS?"],
      ["Una botella de Malbec", "A bottle of Malbec", "OO-nah boh-TEH-shah deh mahl-BEK"],
      ["La cuenta, por favor", "The bill, please", "lah KWEN-tah"],
      ["¿Aceptan tarjeta?", "Do you take card?", "ah-SEP-tahn tar-HEH-tah?"],
      ["¿Cómo llego a…?", "How do I get to…?", "KOH-moh SHEH-goh ah…?"],
      ["Acá está bien", "Here is fine", "ah-KAH es-TAH byen"],
      ["Tengo una reserva", "I have a reservation", "TEN-goh OO-nah rreh-SEHR-vah"],
      ["Más despacio, por favor", "Slower, please", "mahs des-PAH-syoh"],
      ["¡Gracias, buen viaje!", "Thanks, have a good trip!", "GRAH-syahs, bwen VYAH-heh!"],
    ],
    dialogue: [
      { they: "Buenas noches, ¿tienen reserva?", options: ["No, pero ¿hay una mesa para dos?", "Me lo llevo.", "¡Ayuda!"], answer: 0 },
      { they: "¿Qué van a tomar?", options: ["Una botella de Malbec, por favor.", "Dos cuadras.", "Un cuarto kilo."], answer: 0 },
      { they: "¿Pagan con tarjeta o efectivo?", options: ["En efectivo. ¿Hay descuento?", "Jugoso.", "Mucho gusto."], answer: 0 },
      { they: "¡Gracias, chicos! ¡Buenas noches!", options: ["¡Gracias, buenas noches!", "Perdí mi pasaporte.", "Para llevar."], answer: 0 },
    ],
  },
];
